alias ali='vim ~/.bash_aliases'
alias rdwrs='rdw && cd rubyn/rubyspider'
alias b='bundle'
alias hi='history | grep $1'
alias rvc='rvm current'
alias sublime='/home/densom/Downloads/Sublime_Text_2/sublime_text $1'
alias rc='pry -r ./config/environment'
alias koans='cd ~/rails/ruby/koans/koans'
alias pc='pry -r ./config/environment'
alias ca='cd ~/languages/ruby_quize/pp_pascal'
alias cs='pry -f -r./some'

alias xclip='xclip -selection clipboard '
alias le='less'
alias libreoffice='libreoffice &'
alias totem='totem &'
alias pcmanfm='pcmanfm &'
alias wire='sudo -E wireshark'
alias v='gvim'
alias telegram='telegram &'


